#!/usr/bin/env python3
"""Merge all design docs into merged.md, with Open Questions at the end."""
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
DESIGN_DIR = SCRIPT_DIR.parent
OUTPUT = SCRIPT_DIR / "merged.md"

PREFIX_RE = re.compile(r"^(\d+)(?:\.(\d+))?")


def sort_key(path: Path):
    m = PREFIX_RE.match(path.name)
    if not m:
        return (float("inf"), float("inf"), path.name)
    major = int(m.group(1))
    minor = int(m.group(2)) if m.group(2) else 0
    return (major, minor, path.name)


def main():
    files = sorted(
        (p for p in DESIGN_DIR.glob("*.md") if p.name != "Open Questions.md"),
        key=sort_key,
    )
    open_questions = DESIGN_DIR / "Open Questions.md"

    ordered = list(files)
    if open_questions.exists():
        ordered.append(open_questions)

    header_lines = [
        "> **Generated from merged files.** The Packsmith design docs are normally",
        "> maintained as separate files under `design/`. This file is a concatenation",
        "> produced by `design/merge/merge.py` and exists only for convenient linear",
        "> reading. Do not edit this file directly — edits will be overwritten on the",
        "> next merge.",
        ">",
        "> Source files, in order:",
        ">",
    ]
    for p in ordered:
        header_lines.append(f"> - `{p.name}`")
    header = "\n".join(header_lines)

    body_parts = [p.read_text(encoding="utf-8").rstrip() for p in ordered]

    OUTPUT.write_text(header + "\n\n" + "\n\n".join(body_parts) + "\n", encoding="utf-8")
    print(f"Merged {len(ordered)} files -> {OUTPUT.relative_to(DESIGN_DIR.parent)}")


if __name__ == "__main__":
    main()
